#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-python_xlib
Version  : 0.31
Release  : 4
URL      : https://files.pythonhosted.org/packages/40/9c/107e22f637d33434404c07d69112b9d26b76ee0dd4dd705131ab6cdcc818/python-xlib-0.31.tar.gz
Source0  : https://files.pythonhosted.org/packages/40/9c/107e22f637d33434404c07d69112b9d26b76ee0dd4dd705131ab6cdcc818/python-xlib-0.31.tar.gz
Summary  : Python X Library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 LGPL-2.1+
Requires: pypi-python_xlib-license = %{version}-%{release}
Requires: pypi-python_xlib-python = %{version}-%{release}
Requires: pypi-python_xlib-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: python-xlib
Provides: python-xlib-python
Provides: python-xlib-python3
BuildRequires : pypi(pluggy)
BuildRequires : py-python
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(six)
BuildRequires : pytest
BuildRequires : setuptools_scm
BuildRequires : tox
BuildRequires : pypi(virtualenv)

%description
====================
        
        |Build Status| |codecov.io| |Code Health|
        
        `Homepage`_ | `Releases`_ | `Changelog`_
        
        Copyright
        ~~~~~~~~~
        
        The main part of the code is

%package license
Summary: license components for the pypi-python_xlib package.
Group: Default

%description license
license components for the pypi-python_xlib package.


%package python
Summary: python components for the pypi-python_xlib package.
Group: Default
Requires: pypi-python_xlib-python3 = %{version}-%{release}

%description python
python components for the pypi-python_xlib package.


%package python3
Summary: python3 components for the pypi-python_xlib package.
Group: Default
Requires: python3-core
Provides: pypi(python_xlib)
Requires: pypi(six)

%description python3
python3 components for the pypi-python_xlib package.


%prep
%setup -q -n python-xlib-0.31
cd %{_builddir}/python-xlib-0.31

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641485571
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-python_xlib
cp %{_builddir}/python-xlib-0.31/LICENSE %{buildroot}/usr/share/package-licenses/pypi-python_xlib/85db07a9750d8e4e36ee4157eaacc3641234f786
cp %{_builddir}/python-xlib-0.31/debian/copyright %{buildroot}/usr/share/package-licenses/pypi-python_xlib/0af7f6c0527341274366e3d3585047ed554382ec
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-python_xlib/0af7f6c0527341274366e3d3585047ed554382ec
/usr/share/package-licenses/pypi-python_xlib/85db07a9750d8e4e36ee4157eaacc3641234f786

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
